[package]
name = "oxc-py"
version = "0.1.0"
edition = "2021"

[dependencies]
oxc_allocator = "0.44.0"
oxc_codegen = "0.44.0"
oxc_parser = "0.44.0"
oxc_semantic = "0.44.0"
oxc_span = "0.44.0"
oxc_transformer = "0.44.0"
tempfile = "3.17.1"